version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db_datamassive
    ports:
      - "5432:5432"
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - backend

  downloader_base:
    build:
      context: ./data_collection 
      dockerfile: Dockerfile.downloader
    image: image_downloader
    networks:
      - backend
    volumes:
      - ../images:/app/images

  flask_api:
    build:
      context: ./flask_api
      dockerfile: Dockerfile
    container_name: flask-api
    ports:
      - "5080:5000"
    networks:
      - backend
    volumes:
      - ../images:/app/images
    depends_on:
      - db

networks:
  backend:

volumes:
  postgres-data:
