FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

COPY data_collection/image_downloader.py .
COPY data_collection/wikidata_utils.py .

RUN apt-get update && apt-get install -y netcat-openbsd

COPY /wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["python", "image_downloader.py"]
