FROM python:3.10-slim

WORKDIR /app

COPY data_collection/requirements.txt .

COPY data_collection/*.py .

RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["python", "image_downloader.py"]
