FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

COPY visualization/data_analysis.py .
COPY visualization/visualization.py .

COPY config.py .

RUN mkdir -p output

COPY /wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

# ✅ Installer netcat (nécessaire pour wait-for-it.sh)
RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["/wait-for-it.sh", "db", "5432", "--", "sh", "-c", "python data_analysis.py && python visualization.py"]