FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
COPY recommender/recommender.py .
COPY config.py .

COPY wait-for-it.sh /app/wait-for-it.sh
COPY recommender/entrypoint.sh entrypoint.sh

RUN chmod +x /app/wait-for-it.sh ./entrypoint.sh
RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["./entrypoint.sh"]
