FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
COPY recommender/recommender.py .
COPY wait-for-it.sh /app/wait-for-it.sh
RUN chmod +x /app/wait-for-it.sh

RUN apt-get update && apt-get install -y netcat-openbsd

RUN pip install --no-cache-dir -r requirements.txt
COPY /wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

COPY config.py /app/config.py

ENTRYPOINT ["./entrypoint.sh"]