FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

COPY annotation/*.py .

COPY config.py . 

RUN apt-get update && apt-get install -y python3-opencv

RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["python", "generate_annotations.py"]
